#!/bin/bash

ret=0
message=""

# if ci_lint doesn't return 0
if ! poetry run task ci_lint; then
    ((ret+=1))
    message="$message to fix run: poetry run task lint"
fi

# if diff outputs anything
difflen=$(poetry run task isort --diff | wc -l)
if [ "$difflen" -gt 1 ]; then
    ((ret+=1))
    message="$message to fix run: poetry run task isort"
fi

echo "$message"
exit $ret