name: ci

on:
  push:
  schedule:
      - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    # # no docker support on osx images :( 
    # # https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/m-p/39364#M3782
    # # can't run tests, and can't install through brew without interactive shell to install docker desktop
    # - name: Install docker
    #   run: |
    #     brew cask install docker
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    # must be in it's own step, see https://github.com/actions/runner/issues/258
    - name: Install python packages
      run: |
        pipenv install --verbose --dev --skip-lock --python=${{ matrix.python }}
    # - name: Run tests
    #   run: |
    #     pipenv run tests
    - name: Lint with black
      run: |
        pipenv run black --check .