name: ci

on:
  push:
  schedule:
      - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.6]

    steps:
        - uses: actions/checkout@v1
        - name: Install docker
            run: |
            brew install docker docker-machine
        - name: Install virtual box
            run: |
            brew cask install virtualbox
        - name: Set up docker
            run: |
            docker-machine create --driver virtualbox default
            docker-machine env default
            eval "$(docker-machine env default)"
        - name: Set up Python ${{ matrix.python }}
            uses: actions/setup-python@v1
            with:
            python-version: ${{ matrix.python }}
        - name: Install Pipenv
            run: |
            python -m pip install --upgrade pip
            pip install pipenv
        # must be in it's own step, see https://github.com/actions/runner/issues/258
        - name: Install python packages
            run: |
            pipenv install --verbose --dev --skip-lock --python=${{ matrix.python }}
        - name: Run tests
            run: |
            pipenv run tests
        - name: Lint with black
            run: |
            pipenv run black --check .