name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  pypi_release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install flit
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Publish to pypi
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.osxdocker_pypi_api_token }}
      run: |
        flit publish