name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  pypi_release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    # must be in it's own step, see https://github.com/actions/runner/issues/258
    - name: Install python packages
      run: |
        pipenv install --verbose --dev --skip-lock
    - name: Build dist
      run: |
        pipenv run flit build
    - name: Publish to pypi
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.osxdocker_pypi_api_token }}
      run: |
        pipenv run flit publish